using System.Linq;
using System.Numerics;
using Content.Client.Roles;
using Content.Shared._abyss.Health;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Hands.EntitySystems;
using Content.Shared.Inventory;
using Content.Shared.Medical.Healing;
using Content.Shared.Mind.Components;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._abyss.Health.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthWindow : Content.Client.UserInterface.Controls.FancyWindow
{
    private readonly IEntityManager _entMan;
    private readonly SharedHandsSystem _hands;
    private readonly InventorySystem _inventory;
    private readonly IPlayerManager _playerManager;
    private readonly JobSystem _jobSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly SpriteSystem _sprite;
    private readonly IResourceCache _cache;

    private EntityUid? _entity;
    private string? _selectedLimbSlot;

    private static readonly Dictionary<string, string> LimbSlotToLocKey = new()
    {
        { "Head", "abyss-health-part-head" },
        { "Torso", "abyss-health-part-torso" },
        { "LArm", "abyss-health-part-arm" },
        { "RArm", "abyss-health-part-arm" },
        { "LHand", "abyss-health-part-hand" },
        { "RHand", "abyss-health-part-hand" },
        { "LLeg", "abyss-health-part-leg" },
        { "RLeg", "abyss-health-part-leg" },
        { "LFoot", "abyss-health-part-foot" },
        { "RFoot", "abyss-health-part-foot" }
    };

    public HealthWindow()
    {
        RobustXamlLoader.Load(this);
        _entMan = IoCManager.Resolve<IEntityManager>();
        _playerManager = IoCManager.Resolve<IPlayerManager>();
        _jobSystem = _entMan.System<JobSystem>();
        _hands = _entMan.System<SharedHandsSystem>();
        _inventory = _entMan.System<InventorySystem>();
        _prototypes = IoCManager.Resolve<IPrototypeManager>();
        _sprite = _entMan.System<SpriteSystem>();
        _cache = IoCManager.Resolve<IResourceCache>();

        BodyDoll.OnLimbClicked += slot =>
        {
            _selectedLimbSlot = slot;
            BodyDoll.SetSelectedSlot(slot);
            RefreshInjuries();
            RefreshLimbHealthBars();
            RefreshTreatmentItems();
        };
    }

        private bool IsViewerMedical()
    {
        var viewer = _playerManager.LocalEntity;
        if (!viewer.HasValue || !_entMan.TryGetComponent(viewer.Value, out MindContainerComponent? mindContainer) || mindContainer.Mind == null)
            return false;
        var mindId = mindContainer.Mind.Value;
        return _jobSystem.MindHasJobWithId(mindId, "MedicalDoctor")
            || _jobSystem.MindHasJobWithId(mindId, "Paramedic")
            || _jobSystem.MindHasJobWithId(mindId, "ChiefMedicalOfficer");
    }

    private static string GetDamageLevelKey(FixedPoint2 damage, FixedPoint2 max)
    {
        if (damage <= FixedPoint2.Zero) return "abyss-health-damage-none";
        if (max <= FixedPoint2.Zero) return "abyss-health-damage-moderate";
        var ratio = (float)(damage.Double() / max.Double());
        if (ratio < 0.2f) return "abyss-health-damage-light";
        if (ratio < 0.5f) return "abyss-health-damage-moderate";
        if (ratio < 0.85f) return "abyss-health-damage-severe";
        return "abyss-health-damage-critical";
    }


    public void UpdateEntity(EntityUid? entity)
    {
        _entity = entity;
        _selectedLimbSlot = null;
        BodyDoll.SetSelectedSlot(null);

        if (entity is { } uid && uid.IsValid() && _entMan.EntityExists(uid))
        {
            BodyDoll.SetEntity(uid);
            BodyDoll.Visible = true;
            UpdateDamagedSlots(uid);
        }
        else
        {
            BodyDoll.Visible = false;
            BodyDoll.SetDamagedSlots(null);
        }

        RefreshTotalHP();
        RefreshInjuries();
        RefreshLimbHealthBars();
        RefreshTreatmentItems();
    }

    private void RefreshTotalHP()
    {
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value))
        {
            TotalHPLabel.Text = "";
            TotalHPBar.Value = 1;
            TotalHPBar.MaxValue = 1;
            return;
        }

        var uid = _entity.Value;
        if (_entMan.TryGetComponent<AbyssBodyPartHealthComponent>(uid, out var abyss) && abyss.PartMaxHealth != null && abyss.PartDamage != null)
        {
            FixedPoint2 totalMax = FixedPoint2.Zero;
            FixedPoint2 totalDamage = FixedPoint2.Zero;
            foreach (var slot in AbyssBodyPartHealthComponent.LimbSlots)
            {
                totalMax += abyss.PartMaxHealth.GetValueOrDefault(slot);
                totalDamage += abyss.PartDamage.GetValueOrDefault(slot);
            }
            var current = totalMax - totalDamage;
                        var ratio = totalMax > FixedPoint2.Zero ? (float)((totalMax - totalDamage).Double() / totalMax.Double()) : 1f;
            TotalHPBar.MaxValue = 1;
            TotalHPBar.Value = Math.Clamp(ratio, 0, 1);
            if (IsViewerMedical())
                TotalHPLabel.Text = Loc.GetString("abyss-health-total-hp", ("current", current), ("max", totalMax));
            else
            {
                TotalHPLabel.Text = ratio > 0.85f ? Loc.GetString("abyss-health-state-healthy")
                    : ratio > 0.5f ? Loc.GetString("abyss-health-state-injured")
                    : ratio > 0.2f ? Loc.GetString("abyss-health-state-severe")
                    : Loc.GetString("abyss-health-state-critical");
            }

        }
        else if (_entMan.TryGetComponent<DamageableComponent>(uid, out var damageable))
        {
            var total = damageable.TotalDamage;
            var ratio = total > FixedPoint2.Zero ? (float)(total.Double() / damageable.TotalMaxDamage.Double()) : 1f;
            TotalHPBar.Value = Math.Clamp(ratio, 0, 1);
            if (IsViewerMedical())
                TotalHPLabel.Text = Loc.GetString("abyss-health-total-hp", ("current", total), ("max", damageable.TotalMaxDamage));
            else
            {
                TotalHPLabel.Text = ratio > 0.85f ? Loc.GetString("abyss-health-state-healthy")
                    : ratio > 0.5f ? Loc.GetString("abyss-health-state-injured")
                    : ratio > 0.2f ? Loc.GetString("abyss-health-state-severe")
                    : Loc.GetString("abyss-health-state-critical");
            }
        }
        else
        {
            TotalHPLabel.Text = "";
            TotalHPBar.Value = 1;
        }
    }

    private void UpdateDamagedSlots(EntityUid uid)
    {
        if (!_entMan.TryGetComponent<AbyssBodyPartHealthComponent>(uid, out var abyss) || abyss.PartDamage == null)
        {
            BodyDoll.SetDamagedSlots(null);
            return;
        }
        var damaged = AbyssBodyPartHealthComponent.LimbSlots
            .Where(s => abyss.PartDamage.GetValueOrDefault(s) > FixedPoint2.Zero)
            .ToList();
        BodyDoll.SetDamagedSlots(damaged);
    }

    protected override void Opened()
    {
        base.Opened();
                RefreshAll();
    }

    /// <summary>
    /// Refreshes all health data from the current entity (for real-time updates).
    /// </summary>
    public void RefreshAll()
    {
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value))
        {
            TotalHPLabel.Text = "";
            TotalHPBar.Value = 1;
            TotalHPBar.MaxValue = 1;
            BodyDoll.Visible = false;
            BodyDoll.SetDamagedSlots(null);
            InjuriesList.RemoveAllChildren();
            LimbHealthBars.RemoveAllChildren();
            TreatmentItemsList.RemoveAllChildren();
            return;
        }
        var uid = _entity.Value;
        UpdateDamagedSlots(uid);
        RefreshTotalHP();
        RefreshInjuries();
        RefreshLimbHealthBars();
        RefreshTreatmentItems();
    }

    private void RefreshInjuries()
    {
        InjuriesList.RemoveAllChildren();
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value))
        {
            InjuriesList.AddChild(new Label { Text = Loc.GetString("abyss-health-no-data") });
            return;
        }

        var uid = _entity.Value;
        if (!_entMan.TryGetComponent<DamageableComponent>(uid, out var damageable))
        {
            InjuriesList.AddChild(new Label { Text = Loc.GetString("abyss-health-no-data") });
            return;
        }

        if (!string.IsNullOrEmpty(_selectedLimbSlot) && _entMan.TryGetComponent<AbyssBodyPartHealthComponent>(uid, out var abyss) && abyss.PartDamage != null && abyss.PartMaxHealth != null)
        {
            var dmg = abyss.PartDamage.GetValueOrDefault(_selectedLimbSlot);
            var max = abyss.PartMaxHealth.GetValueOrDefault(_selectedLimbSlot);
            var broken = abyss.IsLimbBroken(_selectedLimbSlot);
            var limbName = LimbSlotToLocKey.TryGetValue(_selectedLimbSlot, out var key)
                ? Loc.GetString(key)
                : _selectedLimbSlot;
            var limbText = IsViewerMedical()
                ? $"{limbName}: {dmg} / {max}" + (broken ? " (" + Loc.GetString("abyss-health-limb-broken") + ")" : "")
                : limbName + ": " + Loc.GetString(GetDamageLevelKey(dmg, max)) + (broken ? " (" + Loc.GetString("abyss-health-limb-broken") + ")" : "");
            InjuriesList.AddChild(new Label { Text = limbText });
        }

        var damageDict = damageable.Damage?.DamageDict;
        if (damageDict == null || (damageDict.Count == 0 && string.IsNullOrEmpty(_selectedLimbSlot)))
        {
            if (string.IsNullOrEmpty(_selectedLimbSlot))
                InjuriesList.AddChild(new Label { Text = Loc.GetString("abyss-health-no-injuries") });
            return;
        }

        var totalDmg = damageDict.Values.Aggregate(FixedPoint2.Zero, (a, b) => a + b);
        foreach (var (damageTypeId, amount) in damageDict.OrderByDescending(x => x.Value))
        {
            if (amount <= FixedPoint2.Zero)
                continue;
            if (!_prototypes.TryIndex<DamageTypePrototype>(damageTypeId, out var damageType))
                continue;
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4
            };
            var icon = new TextureRect
            {
                SetSize = new Vector2(20, 20),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                Texture = GetDamageIcon(damageTypeId)
            };
            row.AddChild(icon);
            string damageText;
            if (IsViewerMedical())
                damageText = $"{damageType.LocalizedName}: {amount}";
            else
            {
                var levelKey = GetDamageLevelKey(amount, totalDmg > FixedPoint2.Zero ? totalDmg : (FixedPoint2)1);
                var levelStr = Loc.GetString(levelKey);
                var typeKey = damageTypeId.ToLowerInvariant() switch
                {
                    "blunt" or "slash" or "piercing" => "abyss-health-damage-bruises",
                    "heat" or "cold" => "abyss-health-damage-burn",
                    "bloodloss" or "cellular" => "abyss-health-damage-bleeding",
                    _ => null
                };
                damageText = typeKey != null
                    ? Loc.GetString(typeKey, ("level", levelStr))
                    : Loc.GetString("abyss-health-damage-generic", ("type", damageType.LocalizedName), ("level", levelStr));
            }
            row.AddChild(new Label { Text = damageText });
            InjuriesList.AddChild(row);
        }
    }

    private void RefreshLimbHealthBars()
    {
        LimbHealthBars.RemoveAllChildren();
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value))
            return;
        if (!_entMan.TryGetComponent<AbyssBodyPartHealthComponent>(_entity.Value, out var abyss) || abyss.PartMaxHealth == null || abyss.PartDamage == null)
            return;

        foreach (var slot in AbyssBodyPartHealthComponent.LimbSlots)
        {
            var max = abyss.PartMaxHealth.GetValueOrDefault(slot);
            var dmg = abyss.PartDamage.GetValueOrDefault(slot);
            if (max <= FixedPoint2.Zero)
                continue;
            var name = LimbSlotToLocKey.TryGetValue(slot, out var key) ? Loc.GetString(key) : slot;
            var frac = (float)(1.0 - (dmg / max).Double());
            var bar = new ProgressBar { MinValue = 0, MaxValue = 1, Value = Math.Clamp(frac, 0, 1), HorizontalExpand = true };
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };
            var labelText = IsViewerMedical() ? name : $"{name}: {Loc.GetString(GetDamageLevelKey(dmg, max))}";
            row.AddChild(new Label { Text = labelText, MinSize = new Vector2(50, 0) });
            row.AddChild(bar);
            LimbHealthBars.AddChild(row);
        }
    }

    private Texture? GetDamageIcon(string damageTypeId)
    {
        var path = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var state = damageTypeId.ToLowerInvariant();
        if (!_cache.TryGetResource<RSIResource>(path, out var rsiRes) || !rsiRes.RSI.TryGetState(state, out _))
            state = "unknown";
        return _sprite.Frame0(new SpriteSpecifier.Rsi(path, state));
    }

    private void RefreshTreatmentItems()
    {
        TreatmentItemsList.RemoveAllChildren();
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value))
            return;

        var uid = _entity.Value;
        var damageTypesWithDamage = GetDamageTypesWithDamage(uid);
        var items = CollectHealingItems(uid);

        foreach (var (item, recommended) in items)
        {
            var card = CreateTreatmentCard(item, recommended);
            TreatmentItemsList.AddChild(card);
        }
    }

    private HashSet<string> GetDamageTypesWithDamage(EntityUid uid)
    {
        var set = new HashSet<string>();
        if (!_entMan.TryGetComponent<DamageableComponent>(uid, out var d) || d.Damage?.DamageDict == null)
            return set;
        foreach (var (k, v) in d.Damage.DamageDict)
        {
            if (v > FixedPoint2.Zero)
                set.Add(k);
        }
        return set;
    }

    private bool IsHealingRecommendedForCurrentDamage(EntityUid item, HashSet<string> damageTypesWithDamage)
    {
        if (!_entMan.TryGetComponent<HealingComponent>(item, out var healing))
            return false;
        foreach (var (type, amount) in healing.Damage.DamageDict)
        {
            if (amount < FixedPoint2.Zero && damageTypesWithDamage.Contains(type))
                return true;
        }
        return false;
    }

    private List<(EntityUid item, bool recommended)> CollectHealingItems(EntityUid uid)
    {
        var result = new List<(EntityUid, bool)>();
        if (!_entMan.EntityExists(uid))
            return result;

        var damageTypes = GetDamageTypesWithDamage(uid);

        void AddIfHealing(EntityUid item, bool recommended)
        {
            if (!_entMan.EntityExists(item) || !_entMan.HasComponent<HealingComponent>(item))
                return;
            result.Add((item, recommended));
        }

        if (_entMan.TryGetComponent<Content.Shared.Hands.Components.HandsComponent>(uid, out var hands) && hands.SortedHands != null)
        {
            foreach (var handId in hands.SortedHands)
            {
                if (!_hands.TryGetHeldItem((uid, hands), handId, out var held))
                    continue;
                AddIfHealing(held.Value, IsHealingRecommendedForCurrentDamage(held.Value, damageTypes));
            }
        }

        if (!_entMan.HasComponent<InventoryComponent>(uid) || !_inventory.TryGetSlots(uid, out var slots) || slots == null)
            return result;

        foreach (var slot in slots)
        {
            if (!_inventory.TryGetSlotEntity(uid, slot.Name, out var slotEnt))
                continue;
            var ent = slotEnt.Value;
            if (!_entMan.EntityExists(ent))
                continue;
            AddIfHealing(ent, IsHealingRecommendedForCurrentDamage(ent, damageTypes));

            if (_entMan.TryGetComponent<StorageComponent>(ent, out var storage) && storage.Container != null)
            {
                foreach (var child in storage.Container.ContainedEntities)
                {
                    AddIfHealing(child, IsHealingRecommendedForCurrentDamage(child, damageTypes));
                }
            }
        }

        return result;
    }

    private Control CreateTreatmentCard(EntityUid item, bool recommended)
    {
        var panel = new PanelContainer();
        var inner = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4
        };
        if (!_entMan.EntityExists(item))
            return panel;
        var sprite = new SpriteView { SetSize = new Vector2(32, 32) };
        sprite.SetEntity(item);
        var name = _entMan.GetComponentOrNull<MetaDataComponent>(item)?.EntityName ?? item.ToString();
        var label = new Label { Text = name };
        inner.AddChild(sprite);
        inner.AddChild(label);
        if (recommended)
        {
            var rec = new Label
            {
                Text = Loc.GetString("abyss-health-recommended"),
                FontColorOverride = new Color(100, 255, 100)
            };
            inner.AddChild(rec);
        }
        panel.AddChild(inner);
        return panel;
    }
}
