using System.Linq;
using System.Numerics;
using Content.Client.Interaction;
using Content.Client.Roles;
using Robust.Client.Input;
using Content.Shared._abyss.Health;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Hands.EntitySystems;
using Content.Shared.Inventory;
using Content.Shared.Interaction;
using Content.Shared.Medical.Healing;
using Content.Shared.Mind.Components;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Robust.Shared.IoC;

namespace Content.Client._abyss.Health.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthWindow : Content.Client.UserInterface.Controls.FancyWindow
{
    [Dependency] private readonly IInputManager _inputManager = default!;

    private readonly IEntityManager _entMan;
    private readonly SharedHandsSystem _hands;
    private readonly InventorySystem _inventory;
    private readonly IPlayerManager _playerManager;
    private readonly JobSystem _jobSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly SpriteSystem _sprite;
    private readonly IResourceCache _cache;

    private EntityUid? _entity;
    public EntityUid? CurrentEntity => _entity;
    private string? _selectedLimbSlot;
    private readonly DragDropHelper<DraggedHealingItem> _dragHelper;
    private SpriteView? _dragGhost;
    private EntityUid? _pendingDragItem;
    private bool _pendingDropOnDoll;

    private sealed class DraggedHealingItem
    {
        public readonly EntityUid Uid;
        public DraggedHealingItem(EntityUid uid) => Uid = uid;
    }

    private static readonly Dictionary<string, string> LimbSlotToLocKey = new()
    {
        { "Head", "abyss-health-part-head" },
        { "Torso", "abyss-health-part-torso" },
        { "LArm", "abyss-health-part-arm" },
        { "RArm", "abyss-health-part-arm" },
        { "LLeg", "abyss-health-part-leg" },
        { "RLeg", "abyss-health-part-leg" },
    };

    public HealthWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _entMan = IoCManager.Resolve<IEntityManager>();
        _playerManager = IoCManager.Resolve<IPlayerManager>();
        _jobSystem = _entMan.System<JobSystem>();
        _hands = _entMan.System<SharedHandsSystem>();
        _inventory = _entMan.System<InventorySystem>();
        _prototypes = IoCManager.Resolve<IPrototypeManager>();
        _sprite = _entMan.System<SpriteSystem>();
        _cache = IoCManager.Resolve<IResourceCache>();

        BodyDoll.OnLimbClicked += slot =>
        {
            _selectedLimbSlot = slot;
            BodyDoll.SetSelectedSlot(slot);
            RefreshInjuries();
            RefreshBodyDoll();
            RefreshTreatmentItems();
            TryUseHealingFromActiveHand();
        };

        _dragHelper = new DragDropHelper<DraggedHealingItem>(OnBeginDrag, OnContinueDrag, OnEndDrag);

        OnKeyBindUp += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            if (_dragHelper.Dragged != null)
                _dragHelper.EndDrag();
        };
    }

    private bool OnBeginDrag()
    {
        var dragged = _dragHelper.Dragged;
        if (dragged is null || !_entMan.EntityExists(dragged.Uid))
            return false;
        var uid = dragged.Uid;
        _pendingDragItem = uid;

        _dragGhost?.Orphan();

        _dragGhost = new SpriteView { SetSize = new Vector2(32, 32), MouseFilter = MouseFilterMode.Ignore };
        _dragGhost.SetEntity(uid);
        AddChild(_dragGhost);
        return true;
    }

    private bool OnContinueDrag(float _)
    {
        if (_dragGhost == null)
            return false;

        var dragged = _dragHelper.Dragged;
        if (dragged is null || !_entMan.EntityExists(dragged.Uid))
            return false;

        var screenPos = _dragHelper.MouseScreenPosition.Position;
        var localPos = screenPos - GlobalPosition - _dragGhost.Size / 2;
        LayoutContainer.SetPosition(_dragGhost, localPos);
        _pendingDragItem = dragged.Uid;
        var dollRect = new UIBox2(BodyDoll.GlobalPosition, BodyDoll.GlobalPosition + BodyDoll.Size);
        _pendingDropOnDoll = dollRect.Contains(screenPos);
        return true;
    }

    private void OnEndDrag()
    {
        if (_dragGhost != null)
        {
            _dragGhost.Orphan();
            _dragGhost = null;
        }
        var item = _pendingDragItem;
        var dropOnDoll = _pendingDropOnDoll;
        _pendingDragItem = null;
        _pendingDropOnDoll = false;

        if (!dropOnDoll || item is not { } validItem || _entity is not { } targetEntity || !_entMan.EntityExists(targetEntity) || !_entMan.EntityExists(validItem))
            return;

        // !!! ИСПРАВЛЕНИЕ: Отправляем наш кастомный ивент !!!
        _entMan.RaisePredictiveEvent(new AbyssHealRequestEvent(
            _entMan.GetNetEntity(validItem),
            _entMan.GetNetEntity(targetEntity),
            _selectedLimbSlot));
    }

    private void StartDrag(EntityUid item)
    {
        _dragHelper.MouseDown(new DraggedHealingItem(item));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _dragHelper.Update(args.DeltaSeconds);
    }

    private bool IsViewerMedical()
    {
        var viewer = _playerManager.LocalEntity;
        if (!viewer.HasValue || !_entMan.TryGetComponent(viewer.Value, out MindContainerComponent? mindContainer) || mindContainer.Mind == null)
            return false;
        var mindId = mindContainer.Mind.Value;
        return _jobSystem.MindHasJobWithId(mindId, "MedicalDoctor")
            || _jobSystem.MindHasJobWithId(mindId, "Paramedic")
            || _jobSystem.MindHasJobWithId(mindId, "ChiefMedicalOfficer");
    }

    private static string GetDamageLevelKey(FixedPoint2 damage, FixedPoint2 max)
    {
        if (damage <= FixedPoint2.Zero) return "abyss-health-damage-none";
        if (max <= FixedPoint2.Zero) return "abyss-health-damage-moderate";
        var ratio = (float)(damage.Double() / max.Double());
        if (ratio < 0.2f) return "abyss-health-damage-light";
        if (ratio < 0.5f) return "abyss-health-damage-moderate";
        if (ratio < 0.85f) return "abyss-health-damage-severe";
        return "abyss-health-damage-critical";
    }

    public void UpdateEntity(EntityUid? entity)
    {
        _entity = entity;
        _selectedLimbSlot = null;
        BodyDoll.SetSelectedSlot(null);

        if (entity is { } uid && uid.IsValid() && _entMan.EntityExists(uid))
        {
            BodyDoll.SetEntity(uid);
            BodyDoll.Visible = true;
            RefreshBodyDoll();
        }
        else
        {
            BodyDoll.Visible = false;
            BodyDoll.SetLimbHealthFractions(null);
        }

        RefreshTotalHP();
        RefreshInjuries();
        RefreshBodyDoll();
        RefreshTreatmentItems();
    }

    private void RefreshTotalHP()
    {
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value))
        {
            TotalHPLabel.Text = "";
            TotalHPBar.Value = 1;
            TotalHPBar.MaxValue = 1;
            return;
        }

        var uid = _entity.Value;
        if (_entMan.TryGetComponent<MobStateComponent>(uid, out var mobState) && mobState.CurrentState == MobState.Dead)
        {
            TotalHPBar.MaxValue = 1;
            TotalHPBar.Value = 0;
            TotalHPLabel.Text = Loc.GetString("abyss-health-state-dead");
            return;
        }

        if (_entMan.TryGetComponent<AbyssBodyPartHealthComponent>(uid, out var abyss) && abyss.PartMaxHealth != null && abyss.PartDamage != null)
        {
            FixedPoint2 totalMax = FixedPoint2.Zero;
            FixedPoint2 totalDamage = FixedPoint2.Zero;
            foreach (var slot in AbyssBodyPartHealthComponent.LimbSlots)
            {
                totalMax += abyss.PartMaxHealth.GetValueOrDefault(slot);
                totalDamage += abyss.PartDamage.GetValueOrDefault(slot);
            }
            var current = totalMax - totalDamage;
            var ratio = totalMax > FixedPoint2.Zero ? (float)((totalMax - totalDamage).Double() / totalMax.Double()) : 1f;
            TotalHPBar.MaxValue = 1;
            TotalHPBar.Value = Math.Clamp(ratio, 0, 1);
            if (IsViewerMedical())
                TotalHPLabel.Text = Loc.GetString("abyss-health-total-hp", ("current", current), ("max", totalMax));
            else
            {
                TotalHPLabel.Text = ratio > 0.85f ? Loc.GetString("abyss-health-state-healthy")
                    : ratio > 0.5f ? Loc.GetString("abyss-health-state-injured")
                    : ratio > 0.2f ? Loc.GetString("abyss-health-state-severe")
                    : Loc.GetString("abyss-health-state-critical");
            }

        }
        else if (_entMan.TryGetComponent<DamageableComponent>(uid, out var damageable))
        {
            var total = damageable.TotalDamage;
            var ratio = total > FixedPoint2.Zero ? (float)(total.Double() / damageable.TotalMaxDamage.Double()) : 1f;
            TotalHPBar.Value = Math.Clamp(ratio, 0, 1);
            if (IsViewerMedical())
                TotalHPLabel.Text = Loc.GetString("abyss-health-total-hp", ("current", total), ("max", damageable.TotalMaxDamage));
            else
            {
                TotalHPLabel.Text = ratio > 0.85f ? Loc.GetString("abyss-health-state-healthy")
                    : ratio > 0.5f ? Loc.GetString("abyss-health-state-injured")
                    : ratio > 0.2f ? Loc.GetString("abyss-health-state-severe")
                    : Loc.GetString("abyss-health-state-critical");
            }
        }
        else
        {
            TotalHPLabel.Text = "";
            TotalHPBar.Value = 1;
        }
    }

    protected override void Opened()
    {
        base.Opened();
        RefreshAll();
    }

    public void RefreshAll()
    {
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value))
        {
            TotalHPLabel.Text = "";
            TotalHPBar.Value = 1;
            TotalHPBar.MaxValue = 1;
            BodyDoll.Visible = false;
            BodyDoll.SetLimbHealthFractions(null);
            InjuriesList.RemoveAllChildren();
            TreatmentItemsList.RemoveAllChildren();
            return;
        }
        RefreshBodyDoll();
        RefreshTotalHP();
        RefreshInjuries();
        RefreshBodyDoll();
        RefreshTreatmentItems();
    }

    private void RefreshInjuries()
    {
        InjuriesList.RemoveAllChildren();
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value))
        {
            InjuriesList.AddChild(new Label { Text = Loc.GetString("abyss-health-no-data") });
            return;
        }

        var uid = _entity.Value;
        if (!_entMan.TryGetComponent<DamageableComponent>(uid, out var damageable))
        {
            InjuriesList.AddChild(new Label { Text = Loc.GetString("abyss-health-no-data") });
            return;
        }

        if (!string.IsNullOrEmpty(_selectedLimbSlot) &&
            _entMan.TryGetComponent<AbyssBodyPartHealthComponent>(uid, out var abyss) &&
            abyss.PartDamage != null && abyss.PartMaxHealth != null)
        {
            var dmg = abyss.PartDamage.GetValueOrDefault(_selectedLimbSlot);
            var max = abyss.PartMaxHealth.GetValueOrDefault(_selectedLimbSlot);
            var broken = abyss.IsLimbBroken(_selectedLimbSlot);
            var limbName = LimbSlotToLocKey.TryGetValue(_selectedLimbSlot, out var key)
                ? Loc.GetString(key)
                : _selectedLimbSlot;
            var limbText = IsViewerMedical()
                ? $"{limbName}: {dmg} / {max}" + (broken ? " (" + Loc.GetString("abyss-health-limb-broken") + ")" : "")
                : limbName + ": " + Loc.GetString(GetDamageLevelKey(dmg, max)) + (broken ? " (" + Loc.GetString("abyss-health-limb-broken") + ")" : "");
            InjuriesList.AddChild(new Label { Text = limbText });

            if (dmg <= FixedPoint2.Zero)
                return;
        }

        if (string.IsNullOrEmpty(_selectedLimbSlot))
            return;

        var damageDict = damageable.Damage?.DamageDict;
        if (damageDict == null || damageDict.Count == 0)
            return;

        var totalDmg = damageDict.Values.Aggregate(FixedPoint2.Zero, (a, b) => a + b);
        foreach (var (damageTypeId, amount) in damageDict.OrderByDescending(x => x.Value))
        {
            if (amount <= FixedPoint2.Zero)
                continue;
            if (!_prototypes.TryIndex<DamageTypePrototype>(damageTypeId, out var damageType))
                continue;
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4
            };
            var icon = new TextureRect
            {
                SetSize = new Vector2(24, 24),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                Texture = GetDamageIcon(damageTypeId)
            };
            row.AddChild(icon);
            string damageText;
            if (IsViewerMedical())
                damageText = $"{damageType.LocalizedName}: {amount}";
            else
            {
                var levelKey = GetDamageLevelKey(amount, totalDmg > FixedPoint2.Zero ? totalDmg : (FixedPoint2)1);
                var levelStr = Loc.GetString(levelKey);
                var typeKey = damageTypeId.ToLowerInvariant() switch
                {
                    "blunt" or "slash" or "piercing" => "abyss-health-damage-bruises",
                    "heat" or "cold" => "abyss-health-damage-burn",
                    "bloodloss" or "cellular" => "abyss-health-damage-bleeding",
                    _ => null
                };
                damageText = typeKey != null
                    ? Loc.GetString(typeKey, ("level", levelStr))
                    : Loc.GetString("abyss-health-damage-generic", ("type", damageType.LocalizedName), ("level", levelStr));
            }
            row.AddChild(new Label { Text = damageText });
            InjuriesList.AddChild(row);
        }
    }

    private void RefreshBodyDoll()
    {
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value))
        {
            BodyDoll.SetLimbHealthFractions(null);
            return;
        }

        var uid = _entity.Value;
        if (!_entMan.TryGetComponent<AbyssBodyPartHealthComponent>(uid, out var abyss) || abyss.PartMaxHealth == null || abyss.PartDamage == null)
        {
            BodyDoll.SetLimbHealthFractions(null);
            return;
        }

        var frac = new Dictionary<string, float>(AbyssBodyPartHealthComponent.LimbSlots.Length);
        foreach (var slot in AbyssBodyPartHealthComponent.LimbSlots)
        {
            var max = abyss.PartMaxHealth.GetValueOrDefault(slot);
            var dmg = abyss.PartDamage.GetValueOrDefault(slot);
            if (max <= FixedPoint2.Zero)
            {
                frac[slot] = 1f;
                continue;
            }

            var f = (float)(1.0 - (dmg / max).Double());
            frac[slot] = Math.Clamp(f, 0f, 1f);
        }

        BodyDoll.SetLimbHealthFractions(frac);
    }

    private Texture? GetDamageIcon(string damageTypeId)
    {
        var path = new ResPath("/Textures/_abyss/damage_icons.rsi");
        var state = damageTypeId.ToLowerInvariant();
        if (!_cache.TryGetResource<RSIResource>(path, out var rsiRes) || !rsiRes.RSI.TryGetState(state, out _))
            state = "unknown";
        return _sprite.Frame0(new SpriteSpecifier.Rsi(path, state));
    }

    private void RefreshTreatmentItems()
    {
        TreatmentItemsList.RemoveAllChildren();
        if (!_entity.HasValue || !_entity.Value.IsValid() || !_entMan.EntityExists(_entity.Value) || string.IsNullOrEmpty(_selectedLimbSlot))
            return;

        var uid = _entity.Value;
        var damageTypesWithDamage = GetDamageTypesWithDamage(uid);
        var items = CollectHealingItems(uid);

        foreach (var (item, recommended) in items)
        {
            var card = CreateTreatmentCard(item, recommended);
            TreatmentItemsList.AddChild(card);
        }
    }

    private HashSet<string> GetDamageTypesWithDamage(EntityUid uid)
    {
        var set = new HashSet<string>();
        if (!_entMan.TryGetComponent<DamageableComponent>(uid, out var d) || d.Damage?.DamageDict == null)
            return set;
        foreach (var (k, v) in d.Damage.DamageDict)
        {
            if (v > FixedPoint2.Zero)
                set.Add(k);
        }
        return set;
    }

    private bool IsHealingRecommendedForCurrentDamage(EntityUid item, HashSet<string> damageTypesWithDamage)
    {
        if (!_entMan.TryGetComponent<HealingComponent>(item, out var healing))
            return false;
        foreach (var (type, amount) in healing.Damage.DamageDict)
        {
            if (amount < FixedPoint2.Zero && damageTypesWithDamage.Contains(type))
                return true;
        }
        return false;
    }

    private List<(EntityUid item, bool recommended)> CollectHealingItems(EntityUid uid)
    {
        var result = new List<(EntityUid, bool)>();
        if (!_entMan.EntityExists(uid))
            return result;

        var damageTypes = GetDamageTypesWithDamage(uid);

        void AddIfHealing(EntityUid item, bool recommended)
        {
            if (!_entMan.EntityExists(item) || !_entMan.HasComponent<HealingComponent>(item))
                return;
            result.Add((item, recommended));
        }

        if (_entMan.TryGetComponent<Content.Shared.Hands.Components.HandsComponent>(uid, out var hands) && hands.SortedHands != null)
        {
            foreach (var handId in hands.SortedHands)
            {
                if (!_hands.TryGetHeldItem((uid, hands), handId, out var held))
                    continue;
                AddIfHealing(held.Value, IsHealingRecommendedForCurrentDamage(held.Value, damageTypes));
            }
        }

        if (!_entMan.HasComponent<InventoryComponent>(uid) || !_inventory.TryGetSlots(uid, out var slots) || slots == null)
            return result;

        foreach (var slot in slots)
        {
            if (!_inventory.TryGetSlotEntity(uid, slot.Name, out var slotEnt))
                continue;
            var ent = slotEnt.Value;
            if (!_entMan.EntityExists(ent))
                continue;
            AddIfHealing(ent, IsHealingRecommendedForCurrentDamage(ent, damageTypes));

            if (_entMan.TryGetComponent<StorageComponent>(ent, out var storage) && storage.Container != null)
            {
                foreach (var child in storage.Container.ContainedEntities)
                {
                    AddIfHealing(child, IsHealingRecommendedForCurrentDamage(child, damageTypes));
                }
            }
        }

        return result;
    }

    private Control CreateTreatmentCard(EntityUid item, bool recommended)
    {
        var panel = new PanelContainer { MouseFilter = MouseFilterMode.Stop };
        var inner = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4
        };
        if (!_entMan.EntityExists(item))
            return panel;
        var sprite = new SpriteView { SetSize = new Vector2(32, 32) };
        sprite.SetEntity(item);
        var name = _entMan.GetComponentOrNull<MetaDataComponent>(item)?.EntityName ?? item.ToString();
        var label = new Label { Text = name };
        inner.AddChild(sprite);
        inner.AddChild(label);
        if (recommended)
        {
            var rec = new Label
            {
                Text = Loc.GetString("abyss-health-recommended"),
                FontColorOverride = new Color(100, 255, 100)
            };
            inner.AddChild(rec);
        }
        panel.AddChild(inner);
        panel.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            args.Handle();
            TryUseHealingFromActiveHand(item);
        };
        return panel;
    }

    private void TryUseHealingFromActiveHand(EntityUid? requiredItem = null)
    {
        if (_entity is not { } target || !_entMan.EntityExists(target))
            return;
        if (string.IsNullOrEmpty(_selectedLimbSlot))
            return;

        var viewer = _playerManager.LocalEntity;
        if (viewer is not { } viewerUid || !_entMan.TryGetComponent<Content.Shared.Hands.Components.HandsComponent>(viewerUid, out var hands))
            return;

        var activeItem = _hands.GetActiveItem((viewerUid, hands));
        if (activeItem is not { } held)
            return;

        if (requiredItem.HasValue && requiredItem.Value != held)
            return;

        if (!_entMan.HasComponent<HealingComponent>(held))
            return;

        if (_entMan.TryGetComponent<AbyssBodyPartHealthComponent>(target, out var abyss)
            && abyss.PartDamage != null
            && abyss.PartDamage.GetValueOrDefault(_selectedLimbSlot) <= FixedPoint2.Zero)
        {
            return;
        }

        // !!! ИСПРАВЛЕНИЕ: Отправляем наш кастомный ивент !!!
        _entMan.RaisePredictiveEvent(new AbyssHealRequestEvent(
            _entMan.GetNetEntity(held),
            _entMan.GetNetEntity(target),
            _selectedLimbSlot));
    }
}
